### ISSUE TITLE
Bug: slicing failed on Linux (Luban v4.5.x)

### ISSUE THREAD

**Issue by poltpolt** [Snapmaker/Luban#1900]
# 🐞 bug report

### Affected Version(s)
4.5.0
4.5.1

### Is this a regression? (optional)

It worked in 4.4 on the same system

### To Reproduce
1. Go to 3d printing and add any stl
2. Click on Generate G-Code
3. See error
![obraz](https://user-images.githubusercontent.com/9408405/214316229-54f27917-77f7-4625-b94b-bb0138c404a1.png)

Terminal says : 
2023-01-24T14:02:44.621Z - info service:print3d-slice ../../node_modules/@snapmaker/snapmaker-lunar/engine/Linux/LunarSlicer slice -v -p -o /home/polrus/.config/snapmaker-luban/Tmp/98733365_02621071.gcode -j /home/polrus/.config/snapmaker-luban/Config/printing/active_final.def.json -l /home/polrus/.config/snapmaker-luban/Tmp/71203295_02233068.stl -j /home/polrus/.config/snapmaker-luban/Tmp/71203295_02233068.def.json
2023-01-24T14:02:44.764Z - info service:print3d-slice sliceResult = [object Object]
2023-01-24T14:02:44.764Z - info service:print3d-slice Slicer process exit with code = 2

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: [Opensuse Tumbleweed]
- Printer: [Snapmaker A250]

</code></pre>

**Comment by bclittleua** [comment]
Same issue and error message, clean install of Luban 4.5.1 on a likewise clean install of Win10 Enterprise with an A350T.

**Comment by myperl** [comment]
Same issue an error message. Clean install of Luban 4.5.1  after remove `~/.config/snapmaker-luban `

**Comment by erozen** [comment]
Same issue in 4.5.1.  Ubuntu 22.10, Snapmaker A350.
Fixed by reverting to 4.4.0

**Comment by parachvte** [comment]
We found that it was not enough for us to determine the problem. So we have added logs to repackage a version.

Here is the download link: https://github.com/parachvte/Luban/releases/v4.5.1-log

Please download log in the menu when slicing failed, then send us the saved log.

(Forward from technical support)

**Comment by poltpolt** [comment]
i hope you meant
~/.config/snapmaker-luban/server.log

what caught my attentions is error service:print3d-slice [ERROR] Trying to retrieve setting with no value given: 'fill_perimeter_gaps'

maybe the reason why you don't catch this error is because your configs are migrated from previous versions?
In my case I removed the ~/.config/snapmaker-luban
just to be sure some old values don't interefere

[server.log](https://github.com/Snapmaker/Luban/files/10684061/server.log)

I hope this helps

**Comment by myperl** [comment]
I used a completely fresh install, the ~/.conf/snappmaker-luban directory
didn't exist.

The error still occurs. I can't find the "fill_perimeter_gaps" parameter
anywhere either, neither in Luban nor in the file system:

  snapmaker-luban: find . -type f -name "*.json" -exec grep
"fill_perimeter_gaps" {} \;
  snapmaker-luban:

cu
Thomas

Am Mi., 8. Feb. 2023 um 10:52 Uhr schrieb polpol ***@***.***>:

**Comment by parachvte** [comment]
Thanks for the log, we will release a fix later this week.

**Comment by AdrianQuintanilla** [comment]
Yeah I have a windows 10 brand new installed OS, with 64 bit. 

and I had to revert back to 4.40 in order for the slicer to work in Luban. Took about 45min until I found someone on this form that said to go back to 4.4. 


![Slice Failed](https://user-images.githubusercontent.com/44623160/224520769-336531a0-684b-4b38-9b7a-ab6b85f915a1.PNG)

**Comment by tensile23** [comment]
This issue has been fixed to a large extent in v4.7.2.
https://github.com/Snapmaker/Luban/issues/2071
